# Generated by Django 5.2.17 on 2026-09-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_options_remove_user_first_name_not_empty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrador'), ('agent', 'Agent'), ('citizen', 'Elector')], default='citizen', max_length=20),
        ),
    ]
