# Generated by Django 5.2.17 on 2026-09-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("votecount", "0003_deputiespercountryperparty_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="deputiesperdistrictperparty",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="deputiesperdistrictperparty",
            name="district",
        ),
        migrations.RemoveField(
            model_name="deputiesperdistrictperparty",
            name="party",
        ),
        migrations.AddField(
            model_name="resultpercountryperparty",
            name="deputies",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resultperdistrictperparty",
            name="deputies",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="DeputiesPerCountryPerParty",
        ),
        migrations.DeleteModel(
            name="DeputiesPerDistrictPerParty",
        ),
    ]
