# Generated by Django 5.2.17 on 2026-09-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "votecount",
            "0004_alter_deputiesperdistrictperparty_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="resultpercircunscricaoperparty",
            name="deputies",
            field=models.IntegerField(default=0),
        ),
    ]
