# Generated by Django 5.2.17 on 2026-09-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("votecount", "0005_resultpercircunscricaoperparty_deputies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="district_type",
            field=models.CharField(
                choices=[
                    ("SAO_TOME", "São Tomé e Príncipe"),
                    ("DIASPORA_EUROPE", "Diaspora Europa"),
                    ("DIASPORA_AFRICA", "Diaspora Africa"),
                ],
                default="SAO_TOME",
                max_length=20,
            ),
        ),
    ]
